language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
before_script:
  - psql -c 'CREATE ROLE api login createdb;' postgres
  - psql -U api -c 'CREATE DATABASE splashpage;' postgres
  - git clone git://github.com/gilt/schema-evolution-manager.git
  - cd schema-evolution-manager
  - git checkout 0.9.21
  - cd ../schema
  - ../schema-evolution-manager/bin/sem-apply --host localhost --user api --name splashpage
  - cd ..
script: 
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test
